// FHIR Shorthand MedicationRequest instances generated from sample data
// Generated by generate_medication_requests.py

Instance: bsj1-smp-medrx-glipizide-0-1
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for glipizide - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#310489 "24 HR glipiZIDE 2.5 MG Extended Release Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#52817-385-10

Instance: bsj1-smp-medrx-acetaminophen-0-2
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for acetaminophen - active order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#313782 "acetaminophen 325 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0113-0403-78

Instance: bsj1-smp-medrx-calcium-0-3
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for calcium - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#282465 "calcium carbonate 1250 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#63629-2600-1

Instance: bsj1-smp-medrx-calcium-0-4
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for calcium - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#1310948 "calcium carbonate 1500 MG / cholecalciferol 800 UNT Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#10939-535-44

Instance: bsj1-smp-medrx-carvedilol-0-5
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for carvedilol - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#200031 "carvedilol 6.25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0093-0135-01

Instance: bsj1-smp-medrx-clopidogrel-0-6
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for clopidogrel - active order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#309362 "clopidogrel 75 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#65862-357-30

Instance: bsj1-smp-medrx-colace-0-7
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for colace - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#1247756 "docusate sodium 100 MG Oral Capsule [Colace]"
* medicationCodeableConcept[0].coding[1] = $NDC#68788-8658-1

Instance: bsj1-smp-medrx-ferrous-0-8
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ferrous gluconate - active order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#242590 "ferrous gluconate 240 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#11845-137-51

Instance: bsj1-smp-medrx-ferrous-0-9
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ferrous gluconate - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#310325 "ferrous sulfate 325 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#10135-243-13

Instance: bsj1-smp-medrx-jardiance-0-10
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for jardiance - active order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#1545664 "empagliflozin 10 MG Oral Tablet [Jardiance]"
* medicationCodeableConcept[0].coding[1] = $NDC#0597-0152-07

Instance: bsj1-smp-medrx-lipitor-0-11
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for lipitor - active order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#617320 "atorvastatin 40 MG Oral Tablet [Lipitor]"
* medicationCodeableConcept[0].coding[1] = $NDC#0071-0157-23

Instance: bsj1-smp-medrx-metformin-0-12
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for metformin - active order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#861007 "metFORMIN hydrochloride 500 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#62756-142-02

Instance: bsj1-smp-medrx-nortriptyline-0-13
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for nortriptyline - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#198046 "nortriptyline 50 MG Oral Capsule"
* medicationCodeableConcept[0].coding[1] = $NDC#0121-1971-00

Instance: bsj1-smp-medrx-polyethylene-0-14
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for polyethylene - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#876193 "polyethylene glycol 3350 17000 MG Powder for Oral Solution"
* medicationCodeableConcept[0].coding[1] = $NDC#63739-198-62

Instance: bsj1-smp-medrx-sertraline-0-15
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for sertraline - active order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#312940 "sertraline 25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0143-9656-09

Instance: bsj1-smp-medrx-ondansetron-0-16
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ondansetron - stopped order on 2025-04-22 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-04-22T09:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#198052 "ondansetron 4 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0378-0315-53

Instance: bsj1-smp-medrx-acetaminophen-1-1
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for acetaminophen - active order on 2025-05-03 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-03T14:45:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#313782 "acetaminophen 325 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0113-0403-78

Instance: bsj1-smp-medrx-carvedilol-1-2
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for carvedilol - draft order on 2025-05-03 by PractitionerRole-Physician-PriyaSarkar"
* status = #draft
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-03T14:45:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#200031 "carvedilol 6.25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0781-5223-01

Instance: bsj1-smp-medrx-clopidogrel-1-3
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for clopidogrel - active order on 2025-05-03 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-03T14:45:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#309362 "clopidogrel 75 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0904-6294-61

Instance: bsj1-smp-medrx-ferrous-1-4
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ferrous gluconate - active order on 2025-05-03 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-03T14:45:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#242590 "ferrous gluconate 240 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#11845-137-51

Instance: bsj1-smp-medrx-jardiance-1-5
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for jardiance - draft order on 2025-05-03 by PractitionerRole-Physician-PriyaSarkar"
* status = #draft
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-03T14:45:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#1545664 "empagliflozin 10 MG Oral Tablet [Jardiance]"
* medicationCodeableConcept[0].coding[1] = $NDC#55154-0411-8

Instance: bsj1-smp-medrx-lipitor-1-6
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for lipitor - active order on 2025-05-03 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-03T14:45:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#617320 "atorvastatin 40 MG Oral Tablet [Lipitor]"
* medicationCodeableConcept[0].coding[1] = $NDC#0071-0157-23

Instance: bsj1-smp-medrx-metformin-1-7
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for metformin - active order on 2025-05-03 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-03T14:45:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#861007 "metFORMIN hydrochloride 500 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0093-1048-01

Instance: bsj1-smp-medrx-sertraline-1-8
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for sertraline - active order on 2025-05-03 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-03T14:45:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#312940 "sertraline 25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0143-9656-09

Instance: bsj1-smp-medrx-acetaminophen-1-9
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for acetaminophen - active order on 2025-05-04 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-04T15:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#313782 "acetaminophen 325 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0113-0403-78

Instance: bsj1-smp-medrx-carvedilol-1-10
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for carvedilol - stopped order on 2025-05-04 by PractitionerRole-Physician-PriyaSarkar"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-04T15:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#200031 "carvedilol 6.25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0781-5223-01

Instance: bsj1-smp-medrx-clopidogrel-1-11
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for clopidogrel - active order on 2025-05-04 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-04T15:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#309362 "clopidogrel 75 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0904-6294-61

Instance: bsj1-smp-medrx-ferrous-1-12
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ferrous gluconate - active order on 2025-05-04 by PractitionerRole-Physician-PriyaSarkar"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-04T15:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#242590 "ferrous gluconate 240 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#11845-137-51

Instance: bsj1-smp-medrx-ferrous-1-13
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ferrous gluconate - draft order on 2025-05-04 by PractitionerRole-Physician-PriyaSarkar"
* status = #draft
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-05-04T15:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-Physician-PriyaSarkar)
* medicationCodeableConcept[0].coding[0] = $rxnorm#242590 "ferrous gluconate 240 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#11845-137-51

Instance: bsj1-smp-medrx-jardiance-2-1
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for jardiance - draft order on 2025-05-04 by PractitionerRole-MD-HemaOnko"
* status = #draft
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-01T16:15:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#1545664 "empagliflozin 10 MG Oral Tablet [Jardiance]"
* medicationCodeableConcept[0].coding[1] = $NDC#55154-0411-8

Instance: bsj1-smp-medrx-lipitor-2-2
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for lipitor - active order on 2025-05-04 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-01T16:15:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#617320 "atorvastatin 40 MG Oral Tablet [Lipitor]"
* medicationCodeableConcept[0].coding[1] = $NDC#0071-0157-23

Instance: bsj1-smp-medrx-metformin-2-3
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for metformin - active order on 2025-05-04 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-01T16:15:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#861007 "metFORMIN hydrochloride 500 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0093-1048-01

Instance: bsj1-smp-medrx-polyethylene-2-4
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for polyethylene - active order on 2025-05-04 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-01T16:15:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#876193 "polyethylene glycol 3350 17000 MG Powder for Oral Solution"
* medicationCodeableConcept[0].coding[1] = $NDC#63739-198-62

Instance: bsj1-smp-medrx-sertraline-2-5
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for sertraline - active order on 2025-05-04 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-01T16:15:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#312940 "sertraline 25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0143-9656-09

Instance: bsj1-smp-medrx-acetaminophen-2-6
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for acetaminophen - active order on 2025-07-02 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-02T13:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#313782 "acetaminophen 325 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0113-0403-78

Instance: bsj1-smp-medrx-carvedilol-2-7
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for carvedilol - stopped order on 2025-07-02 by PractitionerRole-MD-HemaOnko"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-02T13:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#200031 "carvedilol 6.25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0781-5223-01

Instance: bsj1-smp-medrx-clopidogrel-2-8
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for clopidogrel - active order on 2025-07-02 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-02T13:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#309362 "clopidogrel 75 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0904-6294-61

Instance: bsj1-smp-medrx-ferrous-2-9
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ferrous gluconate - stopped order on 2025-07-02 by PractitionerRole-MD-HemaOnko"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-02T13:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#242590 "ferrous gluconate 240 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#11845-137-51

Instance: bsj1-smp-medrx-ferrous-2-10
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ferrous gluconate - active order on 2025-07-02 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-02T13:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#702249 "ferrous sulfate 44 MG/ML Oral Solution"
* medicationCodeableConcept[0].coding[1] = $NDC#0536-1400-85

Instance: bsj1-smp-medrx-insulin-2-11
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for insulin - active order on 2025-07-02 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-02T13:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#311048 "insulin isophane, human 70 UNT/ML / insulin, regular, human 30 UNT/ML Injectable Suspension"
* medicationCodeableConcept[0].coding[1] = $NDC#71093-143-11

Instance: bsj1-smp-medrx-jardiance-2-12
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for jardiance - stopped order on 2025-07-02 by PractitionerRole-MD-HemaOnko"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-02T13:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#1545664 "empagliflozin 10 MG Oral Tablet [Jardiance]"
* medicationCodeableConcept[0].coding[1] = $NDC#55154-0411-8

Instance: bsj1-smp-medrx-lipitor-2-13
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for lipitor - active order on 2025-07-02 by PractitionerRole-MD-HemaOnko"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-02T13:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-MD-HemaOnko)
* medicationCodeableConcept[0].coding[0] = $rxnorm#617320 "atorvastatin 40 MG Oral Tablet [Lipitor]"
* medicationCodeableConcept[0].coding[1] = $NDC#0071-0157-23

Instance: bsj1-smp-medrx-lipitor-3-1
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for lipitor - draft order on 2025-07-03 by PractitionerRole-DNP-JudySalas"
* status = #draft
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-03T09:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-DNP-JudySalas)
* medicationCodeableConcept[0].coding[0] = $rxnorm#617320 "atorvastatin 40 MG Oral Tablet [Lipitor]"
* medicationCodeableConcept[0].coding[1] = $NDC#0071-0157-23

Instance: bsj1-smp-medrx-metformin-3-2
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for metformin - active order on 2025-07-02 by PractitionerRole-DNP-JudySalas"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-03T09:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-DNP-JudySalas)
* medicationCodeableConcept[0].coding[0] = $rxnorm#861007 "metFORMIN hydrochloride 500 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0093-1048-01

Instance: bsj1-smp-medrx-metformin-3-3
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for metformin - draft order on 2025-07-03 by PractitionerRole-DNP-JudySalas"
* status = #draft
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-03T09:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-DNP-JudySalas)
* medicationCodeableConcept[0].coding[0] = $rxnorm#861007 "metFORMIN hydrochloride 500 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0093-1048-01

Instance: bsj1-smp-medrx-polyethylene-3-4
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for polyethylene - stopped order on 2025-07-02 by PractitionerRole-DNP-JudySalas"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-03T09:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-DNP-JudySalas)
* medicationCodeableConcept[0].coding[0] = $rxnorm#876193 "polyethylene glycol 3350 17000 MG Powder for Oral Solution"
* medicationCodeableConcept[0].coding[1] = $NDC#63739-198-62

Instance: bsj1-smp-medrx-sertraline-3-5
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for sertraline - stopped order on 2025-07-02 by PractitionerRole-DNP-JudySalas"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-03T09:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-DNP-JudySalas)
* medicationCodeableConcept[0].coding[0] = $rxnorm#312940 "sertraline 25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0143-9656-09

Instance: bsj1-smp-medrx-sitagliptin-3-6
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for sitagliptin - active order on 2025-07-02 by PractitionerRole-DNP-JudySalas"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-03T09:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-DNP-JudySalas)
* medicationCodeableConcept[0].coding[0] = $rxnorm#665042 "sitagliptin 50 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#70710-1900-9

Instance: bsj1-smp-medrx-sitagliptin-3-7
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for sitagliptin - active order on 2025-07-02 by PractitionerRole-DNP-JudySalas"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-03T09:00:00-08:00"
* requester = Reference(PractitionerRole/PractitionerRole-DNP-JudySalas)
* medicationCodeableConcept[0].coding[0] = $rxnorm#665042 "sitagliptin 50 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#70710-1900-9

Instance: bsj1-smp-medrx-acetaminophen-4-1
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for acetaminophen - active order on 2025-07-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-16T11:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#313782 "acetaminophen 325 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0113-0403-78

Instance: bsj1-smp-medrx-clopidogrel-4-2
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for clopidogrel - active order on 2025-07-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-16T11:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#309362 "clopidogrel 75 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0904-6294-61

Instance: bsj1-smp-medrx-ferrous-4-3
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for ferrous gluconate - active order on 2025-07-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-16T11:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#702249 "ferrous sulfate 44 MG/ML Oral Solution"
* medicationCodeableConcept[0].coding[1] = $NDC#0536-1400-85

Instance: bsj1-smp-medrx-insulin-4-4
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for insulin - active order on 2025-07-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-16T11:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#311048 "insulin isophane, human 70 UNT/ML / insulin, regular, human 30 UNT/ML Injectable Suspension"
* medicationCodeableConcept[0].coding[1] = $NDC#71093-143-11

Instance: bsj1-smp-medrx-lipitor-4-5
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for lipitor - stopped order on 2025-07-16 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-16T11:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#617320 "atorvastatin 40 MG Oral Tablet [Lipitor]"
* medicationCodeableConcept[0].coding[1] = $NDC#0071-0157-23

Instance: bsj1-smp-medrx-metformin-4-6
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for metformin - stopped order on 2025-07-16 by Role-IMMD-AnitaChu"
* status = #stopped
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-16T11:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#861007 "metFORMIN hydrochloride 500 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0093-1048-01

Instance: bsj1-smp-medrx-pitavastatin-4-7
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for pitavastatin - active order on 2025-07-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-16T11:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#861652 "pitavastatin calcium 4 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#72603-480-01

Instance: bsj1-smp-medrx-sitagliptin-4-8
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for sitagliptin - active order on 2025-07-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-07-16T11:30:00-08:00"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#665042 "sitagliptin 50 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#70710-1900-9

Instance: bsj1-smp-medrx-jardiance-5-1
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for jardiance - active order on 2025-10-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-10-16T11:02:40.456Z"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#1545664 "empagliflozin 10 MG Oral Tablet [Jardiance]"
* medicationCodeableConcept[0].coding[1] = $NDC#55154-0411-8

Instance: bsj1-smp-medrx-sertraline-5-2
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for sertraline - active order on 2025-10-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-10-16T11:02:40.456Z"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#312940 "sertraline 25 MG Oral Tablet"
* medicationCodeableConcept[0].coding[1] = $NDC#0143-9656-09

Instance: bsj1-smp-medrx-lipitor-5-3
InstanceOf: MedicationRequest
Usage: #example
Description: "MedicationRequest for lipitor - active order on 2025-10-16 by Role-IMMD-AnitaChu"
* status = #active
* intent = #order
* subject = Reference(Patient/patient-betsysmith-johnson01) "Betsy Smith-Johnson"
* authoredOn = "2025-10-16T11:02:40.456Z"
* requester = Reference(PractitionerRole/Role-IMMD-AnitaChu)
* medicationCodeableConcept[0].coding[0] = $rxnorm#617320 "atorvastatin 40 MG Oral Tablet [Lipitor]"
* medicationCodeableConcept[0].coding[1] = $NDC#0071-0157-23
